src/ffi.rs
src/lib.rs
src/main.rs
src/merge_operator.rs
src/rocksdb.rs

I've created a new trait, Writable, which is used to allow the same code to interact directly with the database, or with a WriteBatch. I'm not sure what happens if you insert multiple types of records for the same key into the DB in a single WriteBatch; perhaps that should be forbidden.
You can create a writebatch with `WriteBatch::new()`, and you can write it to the DB using `db::write(batch)`.
This is my first Rust code, so please look at it very carefully--I'm not sure whether I'm correctly freeing the C-allocated writebatch object. If that's being allocated and freed correctly, however, I'm reasonably confident in this implementation.

Add support for WriteBatch

---

src/comparator.rs
src/ffi.rs
src/lib.rs
src/main.rs
src/merge_operator.rs
src/rocksdb.rs
src/rocksdb_options.rs

So, I fixed up the use of borrow and &mut references with the configuration options, with the goal of laying the foundation for exposing the fully configurable read & write APIs, where leaks & API simplicity will be most important.
I started to remove some prefixes from the variables, so that just `use rocksdb` will allow us to write `rocksdb::Options`, `rocksdb::DB`, etc. I hope this is alright; I'll stop doing that if you prefer `use`ing the members of the namespace.

Improve safety of borrow checker with ffi objects

---

src/rocksdb.rs

This changes the DBIterator interface to match the convention of taking
a handle over a string as per the other column-family-aware apis.

Change iterator to take handle

---

README.md
src/lib.rs
src/rocksdb.rs
test/test_iterator.rs

I had an issue where I wanted to store a reference to a `SubDBIterator` on a struct. Because it's created from a `DBIterator`, I ran into an issue where I couldn't store a reference to both the iterator and sub-iterator on the same struct, and couldn't get the `DBIterator` instance to live long enough (see: https://internals.rust-lang.org/t/self-referencing-structs/418)
This PR merges `SubDBIterator` into `DBIterator`. While I was working on it, I fixed a few todos in the code (the DB lifetime one was also confusing).
I can't think of a better name for the `IteratorMode` enum. Also, I am a rust newb :)

More idiomatic iterators?

---

src/comparator.rs
src/ffi.rs
src/lib.rs
src/merge_operator.rs
src/rocksdb.rs
src/rocksdb_options.rs

Using `rustfmt --write-mode overwrite src/lib.rs` to format.

Format  codes.

---

src/rocksdb.rs
test/test_iterator.rs

The `valid()` method could be helpful when we want to know if an iterator is positioned at a kv pair after calling `seek()`.

export `iterator.valid()`

---

Cargo.toml
src/ffi.rs
src/rocksdb_options.rs

@petehunt I've fixed the improper use of u64 in a few places here.  I'd prefer not to use a rocksdb compilation dependency as a few forks do from within this library, because that can be pulled in separately and there is no reason that logic has to live in here.  Let me know if there's anything else that would help in order to get this working for your target!

Bump libc crate to 0.2.10, audit u64 and usize usage in ffi

---

src/ffi.rs
src/lib.rs
src/rocksdb.rs
src/rocksdb_options.rs
test/test.rs
test/test_rocksdb_options.rs

Part of #69
This pull request ports the following changes from @ngaut's fork:
- Add compression option https://github.com/ngaut/rust-rocksdb/pull/8
- Add max_bytes_for_level option https://github.com/ngaut/rust-rocksdb/pull/10
- Add disable_wal option https://github.com/ngaut/rust-rocksdb/pull/11
- Add report_bg_io and compression_per_level options https://github.com/ngaut/rust-rocksdb/pull/19
- Add set_bloom_filter and set_cache_index_and_filter_blocks to BlockBasedOptions https://github.com/ngaut/rust-rocksdb/pull/25
- Add set_level_zero_file_num_compaction_trigger option https://github.com/ngaut/rust-rocksdb/pull/30
- Add set_max_manifest_file_size option https://github.com/ngaut/rust-rocksdb/pull/33
- Add set_wal_recovery_mode option https://github.com/ngaut/rust-rocksdb/pull/34
- …

Cherry pick new options methods from ngaut's fork

---

src/lib.rs
src/merge_operator.rs
src/rocksdb.rs
test/test_column_family.rs

This makes it easier for people who are using the try!() macro to convert errors into their own Error type. It isn't possible to diffrentiate between errors raised from RocksDB and other string errors at the moment.
This adds a simple ``Error`` type that wraps ``String``. People using RocksDB can now implement ``impl From<rocksdb::Error> for MyError`` and add custom behaviour for handling RocksDB errors.
I've implemented ``From<rocksdb:Error> for String`` and added a ``to_string`` method to the ``Error`` type itself to make it easier for those relying on strings to upgrade.

Added an Error type

---

src/rocksdb.rs

Part of #69
This pull request pulls across https://github.com/ngaut/rust-rocksdb/pull/15 which implements a ``path()`` method on ``DB`` that returns the path the ``DB`` was opened with. I've also implemented the ``Debug`` trait for ``DB`` which uses this new method.

Port path() method from ngauts fork and implement Debug for DB

---

src/rocksdb.rs

Part of #69
This pull request ports https://github.com/ngaut/rust-rocksdb/pull/31. I've removed the dead code and there is no longer a need to change the ownership of ``ReadOptions``

Add set_iterate_upper_bound method on ReadOptions

---

src/rocksdb.rs

Part of #69
These changes we're ported from https://github.com/ngaut/rust-rocksdb/pull/22.
The original implementation named the ``len()`` method ``count()``. I renamed it to ``len()`` to be more conventional with Rust.
``count()`` in Rust usually means that you have to actually "count" something that you do not know the length of, such as an iterator. ``len()`` in Rust usually means that you already know the length and can return it quickly. Looking at the [RocksDB source code](https://github.com/facebook/rocksdb/blob/2c1f95291d0142957d74042aea14682539085501/db/write_batch.cc#L12), ``count`` is just a value stored in memory so I think it makes sense for it to be named ``len()`` in the Rust API.

Implement len() and is_empty() methods on WriteBatch

---

src/ffi.rs
src/rocksdb_options.rs

Fixes #79
Deprecated (and removed) as of RocksDB 4.10
https://github.com/facebook/rocksdb/commit/7b79238b655ef6c7ef05c8052c3ded9981c4b54e

Remove Options.set_filter_deletes

---

src/merge_operator.rs
src/rocksdb_options.rs
test/test_column_family.rs

Part of #69 
None of these methods have been in a past released version so I don't think we need to worry about backwards compatibility.
Changes as follows:
- Renamed ``compression`` to ``set_compression_type``. I think this is a much clearer name
- Renamed ``add_merge_operator`` to ``set_merge_operator`` and ``add_comparator`` to ``set_comparator``. Both of these methods replace the entire value of their respective option so "add" is the wrong term to use here.
- Renamed ``set_block_cache_size_mb`` to ``rocksdb_options_optimize_for_point_lookup``. To match RocksDB's API

Improve naming of some of the new Options methods

---

src/db.rs
src/lib.rs
test/test_column_family.rs

The main change is to hide column_family_t behind a containing struct, so there are no raw pointers in the api. Strictly speaking this isn't necesary as the objects are used in an opaque way, but I think it makes the docs nicer.
I've also documented a few things, and marked the DBVector from_c function as unsafe, as the wrong length can cause undefined behaviour

Add some documentation and wrap column_family_t

---

src/db.rs

This change solves the following type mismatch error in 32-bit ARM Linux systems (for example, `armv7-unknown-linux-gnueabihf` target). This is done by replacing type cast `as *const i8` with `as *const c_char` in db.rs.
```
error[E0308]: mismatched types
--> src/db.rs:612:44
|
609 |             ffi_try!(ffi::rocksdb_merge_cf(self.inner,
|             - in this macro invocation
...
612 |                                            key.as_ptr() as *const i8,
|                                            ^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
error[E0308]: mismatched types
--> src/db.rs:614:44
|
609 |             ffi_try!(ffi::rocksdb_merge_cf(self.inner,
|             - in this macro invocation
...
614 |                                            value.as_ptr() as *const i8,
| …
```

Replace cast `as *const i8` with `as *const c_char` to prevent compile errors in 32-bit ARM systems

---

librocksdb-sys/Makefile

The indentation in Makefiles is tabs. Without this change it failed for me with:
Makefile:4: *** missing separator.  Stop

Makefiles use tabs

---

README.md
librocksdb-sys/build.rs

When I tried to build via `cargo build` I saw a lot of error messages and had no clue what was wrong. I hope with this patch things get a little bit clearer if people run into similar issues.

Fail if RocksDB or Snappy source is missing

---

src/backup.rs

In the `BackupEngine` the `create_new_backup` and `purge_old_backups`
methods were private, leading to those warnings.
warning: method is never used: `create_new_backup`, #[warn(dead_code)] on by default
--> src/backup.rs:61:5
|
61 |       fn create_new_backup(&mut self, db: &DB) -> Result<(), Error> {
|  _____^ starting here...
62 | |         unsafe {
63 | |             ffi_try!(ffi::rocksdb_backup_engine_create_new_backup(self.inner, db.inner));
64 | |             Ok(())
65 | |         }
66 | |     }
| |_____^ ...ending here
warning: method is never used: `purge_old_backups`, #[warn(dead_code)] on by default
--> src/backup.rs:68:5
|
68 |       fn purge_old_backups(&mut self, num_backups_to_keep: usize) -> Result<(), Error> {
|  _____^ starting here...
69 | |         unsafe {
70 | | …

Make BackupEngine methods public

---

librocksdb-sys/src/lib.rs
src/db.rs
src/lib.rs
test/test.rs
test/test_raw_iterator.rs

This pull request implements an alternative iterator API that closely matches the underlying the iterators API in RocksDB. It gives access to all the flexibility and performance of RocksDB but the API it implements is quite different to what Rust developers are used to.
This can replace both of by earlier iterator pull requests #70 and #84
Example usage:
```rust
let mut iter = db.raw_iterator();
iter.seek_to_first();
while iter.valid() {
let key = iter.key().unwrap();
let value = iter.value().unwrap();
// ...
iter.next();
}
// Reverse iteration
let mut reverse_iter = db.raw_iterator();
reverse_iter.seek_to_last();
while reverse_iter.valid() {
let key = reverse_iter.key().unwrap();
let value = reverse_iter.value().unwrap();
// ...
reverse_iter.prev();
}
// Fowards iteration from a …
```

Raw iterators

---

CHANGELOG.txt

Makes it clear to 0.6.0 users that they don't have this feature.

Split 0.6.1 release note into its own section

---

src/lib.rs

on my machine (osx 10.12.3) running tests very often fails with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: lock path/for/rocksdb/storage6/LOCK: Resource temporarily unavailable" }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:868
stack backtrace:
```
This error is caused by race condition, cause tests in both `lib.rs` and `db.rs` are reusing database at the same location. This pr fixes that

Fixed race condition in tests

---

librocksdb-sys/src/lib.rs
src/db_options.rs
src/lib.rs

This is removed from rocksdb core as of facebook/rocksdb@eb912a9, and having the reference in the ffi causes loading the shared library to break.
The removal of this function is covered already by #133, but I figured I'd submit this separately in order to get things working for us until the build for that is fixed.

Remove `set_disable_data_sync`

---

src/db.rs
src/db_options.rs
src/lib.rs
tests/test_column_family.rs

I've hit an issue when I create a column family with a custom compare function and then try to 
re-open the same database.  Since I can't pass in options to `open_cf`, my existing column familes
are opened with the default options and I get an error.
This adds a new `DB::open_cf_descriptors` method that allows passing in Options for
each column family, and a new `ColumnFamilyDescriptor` type was added to contain
the congfiguration for each column family.

Add support for opening a column family with options

---

librocksdb-sys/Cargo.toml
src/db_options.rs
src/lib.rs
src/merge_operator.rs
tests/test_column_family.rs

This set of changes depends on the bindgen PR #143
The existing MergeOperator scheme assumes that values are associative and that an existing value is always present in the full_merge operation.  
This PR adds the ability to specify a partial_merge that can be None.  It also does a value check on the merge callback for existing value, and supplies none to the Rust callback if it is null or 0 length. 
This is a minor change to the API, so it might be worth looking into backwards compatible changes.

Non-Associative merge ops

---

src/db.rs
tests/test_iterator.rs

This is a proposal for an API that exposes the ability to limit (db or cf) iterators to key prefixes by using the `prefix_same_as_start` read option. It won't work at all until (or unless!) https://github.com/facebook/rocksdb/pull/3185 lands, but I figured I'd open it here to start discussion on the proposed API.

Preliminary: Allow creating iterators over prefixes

---

src/db.rs
tests/test_iterator.rs

Now when you reverse iterate past the last key, it goes backwards from the end.
When you reverse iterate before the first key, you get nothing out.
Note: This is a breaking change if users have come to depend on the old
behavior.

Fix reverse iteration from a given key

---

librocksdb-sys/build.rs

This PR adds 4 env variables: `ROCKSDB_LIB_DIR`, `SNAPPY_LIB_DIR`, `ROCKSDB_STATIC` and `SNAPPY_STATIC`.
What do you think of this? :)
(related to https://github.com/spacejam/rust-rocksdb/issues/138)

Link with system rocksdb and snappy libs through envvars

---

.travis.yml

A build on macOS is broken now. PR #199 will fix it.

Added travis build on macOS

---

src/checkpoint.rs
src/lib.rs
tests/test_checkpoint.rs

This pull-request adds FFI for [Checkpoints](https://github.com/facebook/rocksdb/wiki/Checkpoints) feature that allows to create snapshots of RocksDB database at specified directory.
Closes #35.
Added `rocksdb::checkpoint` module that provides `Checkpoint` structure with implementation of FFI to RocksDB's [Checkpoints](https://github.com/facebook/rocksdb/wiki/Checkpoints) creation feature.
```rust
// Open existing RocksDB database
let db = DB::open_default("db".to_string()).unwrap();
// Create checkpoint object pointing to this DB
let checkpoint = Checkpoint::new(&db).unwrap();
// Create checkpoint no. 1 of DB
checkpoint.create_checkpoint("cp1".to_string()).unwrap();
// ... do some changes to DB ...
// Create checkpoint no. 2 of DB
checkpoint.create_checkpoint("cp2".to_string()).unwrap(); …
```

Implement Checkpoints

---

src/db_options.rs

Following the suggestion from https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#spinning-disks-usually-provide-much-lower-random-read-throughput-than-flash

Expose 'set_skip_stats_update_on_db_open' option

---

src/lib.rs

ColumnFamily is a marker, I believe it is safe to tag it Send and Sync

Makes ColumnFamily Send

---

src/db_options.rs

This should allow decreasing the [default value](https://github.com/facebook/rocksdb/blob/ddc07b40fc699ab1caead6a04def25fc4e5526de/include/rocksdb/options.h#L560) (currently 1000).

Expose keep_log_file_num option

---

librocksdb-sys/Cargo.toml

I would like to build `rocksdb` with `mozjs`, but cannot
do this bacause of the version conflict.
Everything seems to work fine with the new version.

Bump bindgen up to 0.43

---

README.md

Adding the license badge to make the license stand out a bit more and the "commits since latest release" badge to provided subtle reminder to maintainers of the amount of work not yet released.

Adding license and commits-since release badges

---

README.md

Closes https://github.com/rust-rocksdb/rust-rocksdb/issues/251. It helps to prevent it.

Add requirements and headings

---

src/db.rs
tests/test_column_family.rs

Generic DB.create_cf and test for duplicate column families.

---

src/db.rs

Following https://github.com/rust-rocksdb/rust-rocksdb/commit/21b9a9e98aa5f2d6d3a04cab2cc2dedfa3011fb6.

Update DB::compact_range_cf() arguments to be consistent with other methods

---

src/slice_transform.rs
tests/test_slice_transform.rs

This adopts [pingcap/rust-rocksdb](https://github.com/pingcap/rust-rocksdb)'s SliceTransform [approach](https://github.com/pingcap/rust-rocksdb/blob/master/src/slice_transform.rs), which changes the signature of `transform_fn` from `&[u8] -> Vec<u8>` to `&'a [u8] -> &'a [u8]` while removing the manual `malloc` call we're currently doing in `transform_callback`.
This significantly reduces memory usage, to the point where I wonder if this might actually be a memory leak if rocksdb isn't actually freeing the prefixes that we allocate in `transform_callback`. I might be wrong about this though—see the attached heap dump below.
The main use case for slice transforms is to create prefixes from existing keys, which you don't really need allocations for. However, in theory, the existing API could …

Remove allocations from SliceTransform

---

src/db.rs

the method `ReadOptions.set_iterate_upper_bound` method seems confusing, because the upper_bound is not returned when doing iteration.  some comment are added for this method.

add comment for ReadOptions.set_iterate_upper_bound method.

---

src/db.rs
src/db_options.rs
src/lib.rs

As `rust-rocksdb` already had the `disable_wal` method on `WriteOptions` (see: https://docs.rs/rocksdb/0.12.1/rocksdb/struct.WriteOptions.html#method.disable_wal), it makes sense to implement the `DB::flush()` method that lets the user perform a manual memtable flush to SST files.
This is useful when performing all writes to RocksDB in `disable_wal=true` mode; in such case upon process shutdown (eg. SIGTERM) memtables should be manually flushed to commit changes to disk and avoid data loss.
This `disable_wal` + manual `flush` pattern can be useful on busy servers using RocksDB on SSDs as to minimize SSD write wear.

Add `rocksdb_flush` method on DB

---

librocksdb-sys/Cargo.toml

Hi,
In my app I must use the latest `rust-bindgen` but it conflicts with yours.
so I updated all of the outdated dependencies, what do you think?
the error:
```
Updating crates.io index
error: failed to select a version for `clang-sys`.
... required by package `bindgen v0.47.0`
... which is depended on by `librocksdb-sys v5.18.3`
... which is depended on by `rocksdb v0.12.2`
... which is depended on by `enigma-core-app v0.1.3 (enigma-core/app)`
versions that meet the requirements `^0.27.0` are: 0.27.0
the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.28.0`
... which is depended on by `bindgen v0.49.2`
... which is depended on by `enigma-core-app v0.1.3 (enigma-core/app)`
failed to …
```

Updated librocksdb dependencies

---

src/db_options.rs

Fix the doc according to 
https://github.com/facebook/rocksdb/blob/869ae5d7868d7d48dd55b7be02a23581101ed69a/include/rocksdb/options.h#L295-L306

Fix wrong doc for `set_max_write_buffer_number`

---

CHANGELOG.md
src/db.rs
tests/test_db.rs

As far it is safe to share `Snapshot` between threads I've implemented `Send` and `Sync` for it.
[Snapshot documentations from sources.](https://github.com/facebook/rocksdb/blob/189f0c27aaecdf17ae7fc1f826a423a28b77984f/include/rocksdb/snapshot.h#L15)

Implement Send and Sync for Snapshot

---

src/db.rs

The underlying functionality already existed, but it wasn't exposed to
the top-level API.
This is essentially the same as #288 but exposes the column family iterator instead of the default one

Add raw_iterator_cf_opt to the DB API

---

librocksdb-sys/build.rs

This causes RocksDB to wrap all fs operations using the wide filesystem apis:
<https://github.com/facebook/rocksdb/blob/master/port/win/port_win.h#L345>
Fixes #85 - even though it's already closed.
This problem was originally [punted by RocksDB developers](https://github.com/facebook/rocksdb/issues/3408), but a solution that doesn't require a custom environment was merged in [October last year](https://github.com/facebook/rocksdb/pull/4469).

Build RocksDB with support for unicode filenames on Windows

---

librocksdb-sys/build.rs

Fixes cross-compilation by addressing #322.

enable cross compilation

---

src/db.rs
src/db_options.rs
src/lib.rs

The Send and Sync traits aren't auto-implemented on the many types which
wrap a raw pointer to some RocksDB struct. Most of these types are
nevertheless safe to use in Send and Sync context, so they should be
marked as such

Implement Send and Sync for useful types

---

src/db.rs

Currently the internal code of this function take a pointer to something that can live the scope too early producing a segfault.
https://github.com/hjiayz/rust-rocksdb/blob/7ba1f9d64abdc96c81b1415eb1685470f96e2eac/src/db_options.rs#L82-L90
Here is a simple example of what can happen, "my_key" does not live long enough, it is stored on the stack and the pointer used by `ReadOptions` is dropped at the end of the scope but not the `DBIterator`. Therefore the `DBIterator` segfault when it tries to access to the internal pointer of the "upper_bound" key inside of the now dead `ReadOptions`.
```rust
fn produce_an_iterator(db: &DB) -> DBIterator {
let my_key = "my-super-key";
let options = ReadOptions::default().set_iterate_upper_bound(my_key);
db.iterator_opt(&options).unwrap()
}
```
I would …

Make the set_iterate_upper_bound ReadOptions method unsafe

---

CHANGELOG.md
src/db.rs
src/lib.rs
tests/test_db.rs

In concert with the recently added latest_sequence_number(), this returns an
iterator for the write batches that have occurred since the given sequence.
This API from RocksDB is based on callbacks, and as a result the wrapper
relies on the application implementing a trait that acts as a callback.
cargo test passes

Add get_updates_since() wrapper and its iterator

---

CHANGELOG.md
src/db.rs

Add set_tailing to the ReadOptions struct to support tailing iterators.

---

librocksdb-sys/src/lib.rs

Hi, this is my first, quick and one-liner pull request. Please let me know if anything isn't in good shape!
Currently, `bz_internal_error` is unconditionally and globally defined, which conflicts with other crates in some build situation. So, make it conditional only if needed.
As a background, #209 introduced compile-time conditional bzip2 support as one of other various compressions (ref: https://github.com/rust-rocksdb/rust-rocksdb/pull/209/files#diff-04c6e90faac2675aa89e2176d2eec7d8R17).
Mostly, the newly-added code is covered under respective `feature`s. However, `bz_internal_error` is not (ref: https://github.com/rust-rocksdb/rust-rocksdb/pull/209/files#diff-1da21bb01d3b5631d6399c8da32d163aR26). Obviously, `bz_internal_error` is needed only for the case of `feature = "bzip2"`.

Conditionally define bzip2 error callback function

---

librocksdb-sys/build.rs

This allows this crate to be used on the beta channel.
Generated librocksdb-sys structs no longer implement `Debug`, might have unintented consequences unknown to me.
Feature-gate, or use cfg!.

Disable trait derivation for librocksdb-sys (fixes #335)

---

src/db.rs
tests/test_iterator.rs

Without them, the added simple test case doesn't compile.

Add lifetimes for `DBIterator` return types 

---

src/db.rs
tests/test_raw_iterator.rs

Thanks to Rust's lifetime and borrow checker, it's completely safe to access internal buffer without copying, as any seek operation will need to take `&mut self`.
This PR therefore removes the copying `key` and `value` functions, and replace them with the originally unsafe `key_inner` and `value_inner`.

Avoid copy in DBRawIterator::{key, value}

---

src/db.rs
src/lib.rs
src/merge_operator.rs
tests/test_backup.rs
tests/test_column_family.rs
tests/test_db.rs

Fixes #336 
Fixes #337
Related #294
As posted in #294, `get_pinned` has a huge performance advantage over `get` (current master)
```
test get_large                 ... bench:     153,760 ns/iter (+/- 5,751)
test get_pinned_large          ... bench:       3,147 ns/iter (+/- 203)
test get_pinned_small          ... bench:         141 ns/iter (+/- 5)
test get_pinned_to_owned_large ... bench:       6,804 ns/iter (+/- 485)
test get_pinned_to_owned_small ... bench:         157 ns/iter (+/- 5)
test get_small                 ... bench:         156 ns/iter (+/- 9)
```
There are almost no case where you don't want a pinned get. So to make API simpler, we should always use pinned get and name it `get`. (#337 analyzes the control flow of current get, which internally uses pinned get as well). This PR …

Always use pinnable slice for get operations

---

src/backup.rs
src/checkpoint.rs
src/db.rs
src/ffi_util.rs

Currently to use the macro a trailing comma is required even if the whole usage fits in a single line, which looks slightly awkward. Change the macro a bit so the trailing comma is optional.
Ran `cargo expand` before and after this change, the output is identical.

Improve ffi_try macro to make trailing comma optional

---

src/db_options.rs

I was trying to use this library but realized that this option is missing. It is useful when there are multiple column families, without this the WAL sometimes grows pretty big.

Add set_max_total_wal_size to Options

---

src/db.rs

There is [impl<'_, T> From<&'_ [T]> for Box<[T]> where T: Copy](https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html#impl-From%3C%26%27_%20%5BT%5D%3E), so the following work:
```rust
let slice: &[u8] = &[104, 101, 108, 108, 111];
let boxed_slice: Box<[u8]> = Box::from(slice);
```
Converting into a `Vec` makes no sense, indirect.

feat: simplify conversion on iterator item

---

src/db.rs

The current implementation allows flushing the default column family, but not the rest. This change adds the ability to flush a given column family.

Add flush_cf method to DB

---

src/db.rs

We should not call `next` or `prev` when the internal RocksDB iterator is not valid, otherwise it fails an assertion. The following C++ program demonstrates the behavior:
```
#include <glog/logging.h>
#include <rocksdb/db.h>
int main() {
rocksdb::Options opts;
opts.create_if_missing = true;
char tp[32] = "/tmp/wqfish.XXXXXX";
char* tmpdir = mkdtemp(tp);
rocksdb::DB* db;
auto status = rocksdb::DB::Open(opts, tmpdir, &db);
CHECK(status.ok());
auto* iter = db->NewIterator(rocksdb::ReadOptions());
iter->SeekToFirst();
iter->Next();
delete iter;
delete db;
return 0;
}
```
Output:
```
main: rocksdb/src/db/db_iter.cc:129: virtual void rocksdb::DBIter::Next(): Assertion `valid_' failed.
```
With this change, we check if the iterator is valid in `next` before doing anything else.
Fixes …

Fix potential segfault when calling next on DBIterator that is at the end of the range

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs
librocksdb-sys/src/lib.rs
librocksdb-sys/tests/ffi.rs
src/backup.rs
src/checkpoint.rs
src/compaction_filter.rs
src/db.rs
src/db_options.rs
src/lib.rs
src/merge_operator.rs
src/slice_transform.rs
tests/test_backup.rs
tests/test_checkpoint.rs
tests/test_column_family.rs
tests/test_compationfilter.rs
tests/test_db.rs
tests/test_iterator.rs
tests/test_multithreaded.rs
tests/test_pinnable_slice.rs
tests/test_property.rs
tests/test_raw_iterator.rs
tests/test_rocksdb_options.rs
tests/test_slice_transform.rs
tests/test_write_batch.rs
tests/util/mod.rs

It has been a while since Rust 2018 released and we should be able to do it now :)
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/224

Move to Rust 2018

---

src/db.rs

The function does nothing if the key is not found in DB. See https://github.com/facebook/rocksdb/blob/1dd7873e08c1f55dabb8451f1b8795fcdb012887/include/rocksdb/write_batch.h#L85
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/352
Also note that these `WriteBatch` functions never return `Err`, so maybe we should change all of them to not return `Result`?

Fix doc for WriteBatch::delete

---

src/db.rs
tests/test_db.rs

These APIs never return errors, so they do not need to return `Result`.

Change APIs that never return error to not return Result

---

Cargo.toml
src/db.rs
tests/fail/iterator_outlive_db.rs
tests/fail/iterator_outlive_db.stderr
tests/test_iterator.rs

The current implementation says that the lifetime of the iterator (parameter `'b`) lives at least as long as the lifetime of the DB (parameter `'a`), which is the opposite of what we want. Make it `'a: 'b` instead.
Also add lifetime parameters to a few extra iterator related functions.
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/386
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/356

Fix lifetime parameter for iterators

---

Cargo.toml
tests/test_backup.rs
tests/test_iterator.rs
tests/test_rocksdb_options.rs
tests/util/mod.rs

This ensures no collisions when running tests in a multithreaded manner,
and avoids cluttering up the repo's directory with temp files.
Step one in allowing `cargo watch` to work correctly; more cleanup is
needed before we stop making any files in the repo's directory.
This also helps to prevent bugs where DBPath's drop() could run early
because the DBPath itself (not a reference) was passed into something
like DB::open and dropped immediately, destroying the database.
---
I'm planning to try and get functionality like #250 merged, starting with 
things that are easy to peel off like this. (This is a slightly different approach
from #250 which I hope seems reasonable.)
Easy follow-ups I'm doing in https://github.com/jder/rust-rocksdb/tree/db-path-temp-full
(could be this PR if preferred; …

Make DBPath use tempfile.

---

librocksdb-sys/build.rs

Hey,
snappy's build process usually involves a configuration step which detects whether it is build on a big or little endian system. Since the `librocksdb-sys` uses a `build.rs` that step is skipped and snappy ends up being built for little endian even if on a big endian system. This small patch should change this behaviour.

check for endianness when building snappy

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt
src/db_options.rs

Resolves #378 
Depends on #398 
This PR adds `Options#set_atomic_flush`.

Atomic flush option

---

src/db.rs
src/db_iterator.rs
src/db_options.rs
src/snapshot.rs

This function is probably the only unsafe public API of this library. The unsafe version is not super easy to use since it requires the user to carefully make sure the buffer is alive. For example, the following
usage would be incorrect:
```
let mut opts = ReadOptions::default();
let upper_bound = b"k4".to_vec();
unsafe {
opts.set_iterate_upper_bound(upper_bound);
}
```
A relatively easy way to make it safe is to store the buffer inside `ReadOptions` and store `ReadOptions` inside the iterator, so the buffer will not be dropped when the iterator is being used.
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/299
Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/329

Make set_iterate_upper_bound safe

---

librocksdb-sys/build.rs

This PR:
* Uses the correct names for the zlib and bzip2 libraries. The zlib library is called `libz.a` and the bzip2 library is called `libbz2.a`.
* Only fails on empty sub-module directories when the librocksdb-sys is configured to build them.
* Parameterize the rocksdb include directory.

Fix building librocksdb-sys with system libraries

---

src/db.rs

This change exposes the C APIs that open RocksDB for read only.

Add support for open_for_read_only APIs

---

src/db.rs
tests/test_db.rs

This change adds support for the OpenAsSecondary APIs to open a database
as a secondary. It also adds support for TryCatchUpWithPrimary to allow
clients to synchronize primary and secondary.
/cc @aleksuss 
Signed-off-by: David Calavera <david.calavera@gmail.com>

Add support for open_as_secondary APIs.

---

src/db_options.rs

The current description of this methods sounds like the description for [bottommost_compression](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L229), which we don't expose at the moment. Also the default type is snappy as long as it's enabled: https://github.com/facebook/rocksdb/blob/4cbc19d2a1da1a44775f27c2d167a0d8da0fd9f5/options/options.cc#L99

Update doc for Options::set_compression_type

---

Cargo.toml

This is necessary for the appropriate links to be shown on crates.io, docs.rs, etc.

Add github repo to Cargo.toml

---

.gitignore
tests/test_backup.rs

Migrate everything to use tempdir so we do not create these directories in project root when running tests.

Use DBPath for backup_restore test and remove _rust_rocksdb* from .gitignore

---

librocksdb-sys/build.rs

RocksDB supports up to C++20, so this should be configurable.
I've left the default value as it currently is.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Allow to build RocksDB with a different stdlib.

---

librocksdb-sys/build.rs

I checked build for the most popular Android targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android and  x86_64-linux-android.
The build works fine for aarch64, i686, armv7, but breaks on `x86_64-linux-android` due compiling PCLMUL based code while clang complains about missed target feature `pclmul`.
```
cargo:warning=rocksdb/util/crc32c.cc:667:21: error: '__builtin_ia32_pclmulqdq128' needs target feature pclmul
cargo:warning=  const auto res0 = _mm_clmulepi64_si128(crc0_xmm, multiplier, 0x00);
cargo:warning=                    ^
cargo:warning=/usr/local/Caskroom/android-ndk/21/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/__wmmintrin_pclmul.h:45:13: note: expanded from macro '_mm_clmulepi64_si128'
cargo:warning= …
```

Fixed build for x86_64-linux-android that doesn't support PCLMUL

---

src/db.rs
src/db_options.rs
src/ffi_util.rs
src/lib.rs
src/perf.rs
tests/test_db.rs

This PR:
- Support fetching sst files metadata via api
- Support delete file in range api
- Option to set memtable whole key filtering
- Support api to get approximate memory usage

Support fetching sst files metadata, delete files in range, get mem usage

---

librocksdb-sys/build.rs

This is unnecessary as per the Cargo book:
> Cargo automatically handles whether or not the script itself needs to
> be recompiled, and of course the script will be re-run after it has
> been recompiled. Otherwise, specifying build.rs is redundant and unnecessary.
https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed
Additionally, this sometimes causes the rocksdb being unnecessarily
recomputed whenever I make any change in the downstream project.
And it takes a long time to finish.

librocksdb-sys: do not set rerun-if-changed=build.rs

---

librocksdb-sys/build.rs

This backports the fix from 8a7996e943d4ba56fc32f9e657e8a3cd41b83d1e into `librocksdb-sys` 5.18.3
I'd like to ask for a new release of `librocksdb-sys` with this patch applied (5.18.4 or 5.18.3.1).

Fix building librocksdb-sys with system libraries (#393)

---

.github/workflows/rust.yml

Added a workaround which removes directory with invalid `libclang.dll` library. Suggested by https://github.com/actions/virtual-environments/issues/2208

Fix build on windows host

---

librocksdb-sys/Cargo.toml

Some features of bindgen are not needed when building the library and
lead to unused dependencies (mainly `clap`). This change deactivates all
`bindgen` features except for `runtime` which is required for build to
work.
This improved debug build time by ~13 seconds and (surprisingly) release
build time by ~9 seconds. But perhaps improved security is more
interesting.
I can post the outputs from `-Z timings` somewhere if you want, but I don't know where to put it to be accepted and rendered - LMK if you know of a good website. The files have above 200-250k.
I intend to backport this into 12.2 after it's accepted.

Removed unneeded bindgen features

---

librocksdb-sys/Cargo.toml

Some features of bindgen are not needed when building the library and
lead to unused dependencies (mainly `clap`). This change deactivates all
`bindgen` features except for `runtime` which is required for build to
work.
I had to bump bindgen for it to have effect, so I'm not sure if your want to do such change in this branch. If not I would understand it.

Removed unneeded bindgen features (backport)

---

src/db_options.rs

https://github.com/rust-rocksdb/rust-rocksdb/pull/457  make a change
> The merge result Vec<u8> is turned into a boxed slice and turned into raw pointer by Box::into_raw. In delete_callback, Box::from_raw is called to wrap the raw pointer back and the original memory will be released here.
https://github.com/rust-rocksdb/rust-rocksdb/pull/481 omit `delete_callback` by mistake.
According
```
if (delete_value_ != nullptr) {
(*delete_value_)(state_, tmp_new_value, new_value_len);
} else {
free(tmp_new_value);
}
```
https://doc.rust-lang.org/std/boxed/struct.Box.html#method.into_raw
https://doc.rust-lang.org/nomicon/ffi.html#destructors
I think this is UB.
fix https://github.com/rust-rocksdb/rust-rocksdb/issues/494

fix: merge delete_callback omitted by mistake

---

src/checkpoint.rs
src/db.rs
src/db_options.rs
src/perf.rs
tests/fail/checkpoint_outlive_db.rs
tests/fail/checkpoint_outlive_db.stderr
tests/fail/snapshot_outlive_db.rs
tests/fail/snapshot_outlive_db.stderr
tests/test_checkpoint.rs
tests/test_db.rs

Fix #462.
- Add a lifetime to `Checkpoint` to ensure that it does not outlive the `DB`
- Wrap `Cache` and `Env` in an `Rc` and keep a copy of that in the database to ensure that they are not dropped before the database is.
This add two auxiliary structs where to keep `Cache` and `Env` that are set using `set_row_cache` in `Options` or `set_block_cache`, `set_block_compressed` in `BlockBasedOptions`. When a `DB` is open this structs are cloned and kept in the database to ensure the lifetime requirements are met.
This approach allow us to have an unchanged api (with the exception of `Checkpoint` life time) but the compiler will not help us if we forget to keep track of something. Implementing this with lifetime will require to have four lifetimes parameters in (at least), `Options`, …

Keep Cache and Env alive with Rc

---

CHANGELOG.md
src/db.rs
tests/test_db.rs

Added the ability to open a database with column families and TTL. It uses method `ffi::rocksdb_open_column_families_with_ttl`.

Add DB::open_cf_with_ttl method.

---

src/db.rs
tests/test_db.rs

Make multi_get return Vec<Result> instead of Result<Vec>.
See #502 for details.

Fix multi_get

---

src/db_options.rs
src/lib.rs
tests/test_db.rs

RocksDB supports a cuckoo table format, for fast point queries on datasets with fixed key and value length. Unfortunately, the current version of `rust-rocksdb` does not support creating a new table with this format. 
This PR adds the necessary Rust APIs for that, and nothing more (as everything was already available from the ffi).

Add support for the cuckoo table format

---

src/db_options.rs
src/lib.rs

Similarly to other types in `db_options.rs`, `Cache` and `Env` are Send-safe and Sync-safe.

Mark Cache and Env as Send and Sync

---

src/db_options.rs

These types can be shared between multiple instances, but the currently
it's hard to do so.

Allow cloning the Cache and Env

---

CHANGELOG.md
librocksdb-sys/build.rs

Since `0.12.3`/gh-295 the underlying library gets compiled with SSE4.1/SSE4.2/PCLMUL instructions unconditionally.
This prevents building the library for backwards compatible binaries, e.g., for `target-cpu=nocona` you'd want a binary without SSE4 instructions.
With the changes proposed here, one still can freely build for `target-cpu=nehalem` (or `target-cpu=westmere` to get PCLMUL), or just `target-cpu=native` given a recent enough machine and for local deployment. And additionally `target-cpu=nocona` would yield the desired compatible build.
(Context here is that `rust-rocksdb` is used by some programs we distribute as binaries for [Bioconda](https://bioconda.github.io) and currently/usually target older CPU architectures there.)

Make SSE inclusion conditional for target features

---

librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

One important change this release contains is exposing the flush WAL API over the C API.

Update RocksDB to v6.22.1

---

src/db.rs
src/db_options.rs

Exposes the WAL flush API. More information about this API can be found here[1].
[1] https://rocksdb.org/blog/2017/08/25/flushwal.html

Add WAL flush API

---

.github/workflows/rust.yml
Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs

RocksDB includes some optimizations when it's compiled with jemalloc. This PR allows enabling jemalloc using new `jemalloc` feature.

Support building RocksDB with jemalloc

---

CHANGELOG.md
librocksdb-sys/build.rs

This re-adds support for UTF-8 file paths on Windows, which was removed in #493 
Fixes #512 
Fixes #85 (already closed)

Support UTF-8 file paths on Windows

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs

We have an advanced use case with [Estuary Flow](github.com/estuary/flow) where we're interoperating Go and Rust within a single process, and wish to use this crate to actually build RocksDB, while linking it using the `go` toolchain.
We've gotten this working by having the `librocksdb-sys` crate publish metadata which dependent crates can utilize to locate the RocksDB include sources and the libraries built by this crate.
Our use case also requires the RTTI compile-time flag of RocksDB, which is disabled by default. I've added this as a feature flag.

add feature flag for runtime type information, and metadata for locating library and sources

---

src/merge_operator.rs
tests/test_column_family.rs
tests/test_merge_operator.rs

Rework merge operands iterator. 
`&mut` is not needed, so you can iterate several times over the iterator.
In our specific use case, it gave speedup up to 80% due to lack of realocations.

Add merge operands iterator

---

src/backup.rs
tests/test_backup.rs

The current BackupEngine in src/backup.rs can only restore from the latest (`fn restore_from_latest_backup()`) and miss a method to restore from a specified backup id. As we can see, the rocksdb ffi `rocksdb_backup_engine_restore_db_from_backup` is provided in librocksdb-sys.
This pull request makes it to support restoring from a specified backup.
Related to issue #560

Support restoring from a specified backup

---

src/db_options.rs

Rename set_background_purge_on_interator_cleanup to set_background_purge_on_iterator_cleanup

fix ReadOptions method typo

---

src/db.rs

Avoids an allocation by merging two of the vectors into a vector of tuples. The components are later referenced by dedicated vectors, anyway.
Also allows using `unzip()`, just like in `multi_get_opt()`. This avoids reallocations by using the size hint for `keys` internally.

Optimize multi_get_cf_opt() to use size hint

---

src/ffi_util.rs

A newly allocated vector cannot overlap with the source, so the copy can be optimized slightly. Also [reordered](https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec) the copy and `set_len()`.

Optimize non-overlapping copy in raw_data

---

librocksdb-sys/tests/ffi.rs
src/db_options.rs
src/merge_operator.rs

Using more specific conversions is preferable, where possible.

Replace mem::transmute with narrower conversions

---

src/column_family.rs
src/db.rs
src/db_options.rs
src/ffi_util.rs
src/lib.rs
tests/test_column_family.rs
tests/test_property.rs

Make `CacheWrapper` and `EnvWrapper` Send and Sync

---

src/lib.rs
src/properties.rs
tests/test_property.rs

I want to query several properties and noticed there aren't equivalent constants as there are in the RocksDB repo.
This was a copy/paste with some regex'ing to make it adhere to Rust syntax. I figured including the comments inline is nice, but I could also see argument of not including them and instead referring reader to the block starting at:
https://github.com/facebook/rocksdb/blob/08809f5e6cd9cc4bc3958dd4d59457ae78c76660/include/rocksdb/db.h#L428

Add constants for all supported properties

---

src/db_options.rs

Weirdly, RocksDB C interface does not have a way to just set the
`enabled` flag of the bottommost compression options so I’ve decided
to replicate that interface in Rust as well.  As far as I understand,
this unfortunately means that to set bottommost compression one needs
to set the type and then also use one of the other methods for
configuring the compression.
Issue: https://github.com/rust-rocksdb/rust-rocksdb/issues/260
Issue: https://github.com/near/nearcore/issues/6119

Support configuring bottom-most compression level

---

src/column_family.rs

As far as I can tell, there is no guarantee that `Arc<T>` can be soundly transmuted to `Arc<U>`, even if `T` can be soundly transmuted to `U`.
Looking at the implementation of `Arc`, it is effectively a single field struct, wrapping a private `NonNull<ArcInner<T>>` where `ArcInner<T>` is `#[repr(C)]`, so the transmute is not UB as of now, and of course it's unlikely that this would change. But it's still not good to rely on such an implementation detail for soundness.

Fix theoretical UB while transmuting Arc

---

src/properties.rs

Fixing a typo from https://github.com/rust-rocksdb/rust-rocksdb/pull/589 that added extra prefix to one of the property strings (thus making it invalid) - kudos to @niklasf for [catching the mistake](https://github.com/rust-rocksdb/rust-rocksdb/commit/daee3d636c575fef60d93e448a8e1078afd7c041#r65861692).

fixup! Add constants for all supported properties (#589)

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt
librocksdb-sys/tests/ffi.rs
src/db.rs
src/db_options.rs
tests/test_db.rs

Upgrades to the latest RocksDB [release](https://github.com/facebook/rocksdb/releases/tag/v6.28.2).
6.28.2 removed some of the C API functions, which were also removed from rust-rocksdb:
- [rate_limit_delay_max_milliseconds](https://github.com/facebook/rocksdb/pull/9455)
- [soft_rate_limit/hard_rate_limit](https://github.com/facebook/rocksdb/pull/9452)
- [set_purge_redundant_kvs_while_flush](https://github.com/facebook/rocksdb/pull/9429)
- [set_skip_log_error_on_recovery](https://github.com/facebook/rocksdb/pull/9434)
Added `column_family_name` to `LiveFile` - allowed by recently added C API `rocksdb_livefiles_column_family_name`.

Upgrade to RocksDB 6.28.2

---

src/db.rs
tests/test_db.rs

I saw there is already `open_cf_with_opts_for_read_only()`; however, I also saw the existence of `open_cf_descriptors_with_ttl()` so I thought adding `open_cf_descriptors_read_only()` was fair game; there is no alternative to open CF's as a secondary with non-default options so `open_cf_descriptors_as_secondary()` seemed like a reasonable addition as well.
I saw that https://github.com/rust-rocksdb/rust-rocksdb/pull/601 already exists; it'd be awesome if this could sneak into 0.18.0 (assuming you all agree with the additions), but understandable if its' too late.

Add open_cf_descriptor methods for Seoncdary and ReadOnly AccessType

---

src/db.rs
src/snapshot.rs
tests/test_pinnable_slice.rs

`PinnableSlice` based API is implemented for `DBWithThreadMode` in https://github.com/rust-rocksdb/rust-rocksdb/pull/246, but not for `SnapshotWithThreadMode`.
This PR adds `get_pinned`, `get_pinned_cf`, `get_pinned_opt`, `get_pinned_cf_opt` methods to the `SnapshotWithThreadMode`.

Add Snapshot PinnableSlice based API

---

librocksdb-sys/src/lib.rs

Fix: https://github.com/rust-rocksdb/rust-rocksdb/issues/609
The `bz_internal_error` was introduced when  [bzip2 support was added](https://github.com/rust-rocksdb/rust-rocksdb/pull/209), the bzip2-sys crate was not used at that time.
This function should be removed after [using bzip2-sys crate](https://github.com/rust-rocksdb/rust-rocksdb/pull/555), otherwise it will conflict with the definition in bzip2-sys when compiled with lto enabled.

fix: 'bz_internal_error': symbol multiply defined!

---

src/db.rs
src/db_options.rs
src/ffi_util.rs
src/lib.rs
src/slice_transform.rs
tests/test_property.rs

Methods such as property_value take `&str` name as argument.  However,
since they interact with C functions, such string arguments need to be
converted into a `&CStr`.  Because the argument is `&str` this must be
done via `CString::new` which needs to allocate memory and verify that
the value does not have embedded NUL bytes.  Even if the caller
already has a `&CStr` there is no way to pass it directly to the
function and a needless allocation happens.
This commit introduces a `CStrLike` trait which can be used in place
of `&str` arguments.  A function which accepts `impl CStrLike` as an
argument can be called either with `&str` or `&CStr` which allows it
to take the C string directly if it’s passed.
Note that this is strictly speaking backwards-incompatible change.
While call sites such …

Allow passing &CStr arguments

---

src/properties.rs
tests/test_property.rs

Now that property_value et al accept &CStr arguments (via the use of
CStrLike trait), change properties to use &CStr type.  This way, if
someone calls `db.property_value(properties::STATS)` (which is the
most obvious and ergonomic way to use the property definitions) they
don’t have to pay the price of allocating temporary CString.
Furthermore, replace ‘at level’ property name prefixes with functions
which take level as an argument and return a property name.  This is
a simpler interface than providing a &CStr prefix and expecting user
to append the level index since user would have to deal with &CStr not
being Display.
Note that this is a breaking change.  While uses which don’t care
about the type of properties and simply passed them as arguments to
DB::property_value method will work, …

Convert properties to &CStr

---

librocksdb-sys/Cargo.toml

When using `rocksdb`, it is not possible to use another rust crate that depends on a more recent version of `zstd-sys`, because of a major version conflict[^1].
```diff
-zstd-sys = { version = "1.6", default-features = false, optional = true }
+zstd-sys = { version = "2.0", features = ["zdict_builder"], optional = true }
```
Updates `zstd-sys` from `1.6` to `2.0` in `librocksdb-sys`. We additionally add the `zdict_builder` feature flag. Reading through the `zstd-rs` [commit log](https://github.com/gyscos/zstd-rs/commits/master/zstd-safe/zstd-sys), the reason for the breaking change is as follows:
```
commit 3a6c7fa76b49928bd4afc6a68ae82fce842df8dd (tag: v0.11.0)
Author: Alexandre Bury <alexandre.bury@gmail.com>
Date:   Wed Mar 9 15:48:49 2022 -0500
Bump version to 0.11.0
zstd-sys 2.0.0 …
```

Update `zstd-sys` from `1.6` to `2.0`

---

tests/test_db.rs
tests/test_iterator.rs
tests/test_slice_transform.rs
tests/util/mod.rs

Firstly, introduce helper assert_iter and assert_iter_reversed
functions to reduce code repetition.  This will be especially useful
in upcoming commit which changes the Item type of the iterator.
Secondly, keep keys and values declared at the start of some of the
tests as slices without boxing them.  Doing the latter introduces
conveluted syntax such as `&*k1`; keeping them as slices simplifies
the syntax and also allows them to be converte into constsants.
Lastly, replace `cba` helper function with `pair` which construct
a pair of boxed slices.  This removes some repetition since after
the previous point `cba` was only ever used in a pair.

Refactor iterator-related tests

---

src/db_iterator.rs
src/db_options.rs

Once iterator is created, ReadOptions.inner is no longer accessed by
the C code (the C iterator copies the options).  Only the lower and
upper bounds need to be kept around since the inner iterator holds
only pointers to them (i.e. borrows them).  It’s thus enough to keep
the bounds around; the inner objects can be safely dropped.
Change DBRawIteratorWithThreadMode to store just the bounds which
saves one pointer worth of space from the struct and allows inner
read options object to be freed as soon as iterator is created.

Don’t hold onto ReadOptions.inner when iterating

---

src/db_iterator.rs
src/db_options.rs

Turns out there’s a two-step reference chain for lower and upper bound.
The C++ ReadOptions refer slices inside of the rocksdb_readoptions_t
C wrapper which refer to Rust vectors.   Holding onto the vectors is
insufficient for all the references to be valid.
This reverts commit 947e4b63034fff2151f52c399a5d85925ea80911.
Fixes: https://github.com/rust-rocksdb/rust-rocksdb/issues/660

Revert "Don’t hold onto ReadOptions.inner when iterating"

---

librocksdb-sys/Cargo.toml

The `static` feature flag needs to set feature flags in dependencies. Unfortunately this unconditionally pulls in the dependency, even if it would not otherwise be enabled/needed.
Rust 1.60 [introduces weak dependency features](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features) for this exact use case.
Do we have a policy about the minimum supported Rust version?

Avoid pulling in dependencies via static feature flag

---

librocksdb-sys/tests/ffi.rs
src/db_options.rs
src/db_pinnable_slice.rs
src/lib.rs
src/perf.rs

* Eagerly derive common traits
* Clarify deref
* Remove unused functions from FFI test

Fix clippy warnings

---

src/backup.rs

This allows `create_new_backup` for `OptimisticTransactionDB<T: ThreadMode>`.

make `create_new_backup_flush` generic

---

.gitmodules
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs
librocksdb-sys/src/lib.rs

Thanks to https://github.com/10XGenomics/lz4-rs/pull/27 it is now
possible to use the lz4-sys crate instead of a submodule.
This allows other crates to also link lz4.
Additionally, the latest version fixes CVE-2021-3520. I don't think it
was possible to exploit this in RocksDB, because RocksDB will only
decompress payloads it has previously compressed itself.

Use lz4-sys crate (fixes #666, fixes #617, fixes #575)

---

librocksdb-sys/build.rs

Currently a change in linkage mode env vars will not trigger a re-run of the `build.rs`-binary, and hence compilations fail until the that binary is deleted or other triggers are manually triggered.
To my understanding, it's a mere lag of 3 lines telling cargo to re-run the build script on env var change.
Also adds the option to _NOT_ link statically if i.e. `ROCKSDB_STATIC=false` is provided

make sure build.rs is re-run, when env vars change

---

.gitignore
src/transactions/transaction_db.rs
tests/test_column_family.rs

Since `TransactionDB` is a subclass of `StackableDB` which is subclass of `DB`, there's no reason for the `drop_cf` function should be callable directly from TransactionDB.
The core of this change is a cast in `transaction_db.rs`:
```rust
self.inner as *mut ffi::rocksdb_t,
```
The PR also includes a test, but that's mostly copy-pasted from a similar test on `DB`, with the addition of testing for error when opening a previously deleted column family to make sure that the drop was actually successful.

Add drop_cf function to TransactionDB

---

src/db_options.rs

Good day!
I'm writing my database on top of rocks db. And I have a problem:
I want to cache snapshot (for consistency) iterator between different batch requests for stream processing, but current implementation requires lifetime and lifetime is incompatible with caching.
I'd like to do simple workaround via ReadOptions, but method set_snapshot is private. So I want to make it public =)
my current solution is:
```rust
let db: &'static DB = todo!();
let  column_family: &'static ColumnFamily = todo!();
let snapshot = db.snapshot();
let mut options = rocksdb::ReadOptions::default();
options.set_snapshot(&snapshot);
let iter = db.raw_iterator_cf_opt(column_family, options);
```

Make set_snapshot public (simple pull request)

---

src/compaction_filter.rs
tests/test_compationfilter.rs

In the current implementation, reference to static variable is expected in `Decision::Change` variant, making it impossible to update the value based on a runtime context (what that value was holding, for example). RocksDB supports value changing, and static bound seems to be too restrictive.

compaction filter: allow to pass in owned variable for Decision::Change variant

---

librocksdb-sys/build.rs

Fix #681 
delete 'config.define("HAVE_UINT128_EXTENSION", Some("1"));' in [build.rs](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L236), which can cause Issue #681 
Not all compilers support the type of int128, so the https://github.com/facebook/rocksdb/pull/7338 uses makefile to check int128 compatibility. The type of int128 is not related to target, but related to compiler。

Fix int128 compatibility check(Issue #681)

---

src/backup.rs
src/db_options.rs
src/env.rs
src/lib.rs
tests/test_backup.rs

The main objective of this PR is to support `rocksdb_backup_engine_options_t` (introduced in https://github.com/facebook/rocksdb/commit/78aee6fedc62ca6048e500969912d1e1f0553490) so that we can call the associated `rocksdb_backup_engine_options_set_max_background_operations` function and achieve higher parallelism for backup and restore operations (notably, the current parallelism is 1, meaning that rocksdb will only copy/checksum/hardlink/whatever 1 file at a time, which is insufficient for rocksdb to full utilize hardware on even modest machines).
One side-effect of this PR is that the signature for BackupEngine::open changes from `open<P: AsRef<Path>>(opts: &BackupEngineOptions, path: P)` to `open(opts: &BackupEngineOptions, env: &Env)`. This may cause some consumer code to fail to …

Support RocksDB 7.x BackupEngineOptions

---

librocksdb-sys/build.rs

Building this crate on `arm-linux-gnueabihf` is fine, HOWEVER, opening a rocksdb database using the built code fails:
On our CI, we get a "Value too large for defined data type" in our functional tests, see [build output](https://build.bitcoinabc.org/repository/download/BitcoinABC_BitcoinAbcStaging/515561:id/artifacts.tar.gz!/functional/test_runner_%E2%82%BF%E2%82%B5_%F0%9F%8F%83_20230302_193244/chronik_block_214/node0/regtest/debug.log) (you can login as guest if necessary).
After a bit of digging, it turns out this refers to a [missing environment variable specifically for 32-bit systems that want to open files using 64-bit offsets](https://stackoverflow.com/a/23372153).
Therefore, this PR [fixes our build](https://build.bitcoinabc.org/viewLog.html?buildId=515991&buildTypeId=BitcoinABC_B …

Fix 32-bit ARM build

---

librocksdb-sys/build.rs

When attempting to build `librocks-sys` using `rustc_codegen_cranelift`, you encounter a panic error caused by an `unwrap` function in the `build.rs` file. The error occurs because the `unwrap` function is attempting to access the `CARGO_CFG_TARGET_FEATURE` environment variable, which is not available in the cranelift platform.
This PR adds a condition to check that the env variable actually exists instead of unwrapping it.

Enable librocksdb-sys to be built by rustc_codegen_cranelift

---

src/db_options.rs
src/perf.rs
tests/test_db.rs
tests/test_rocksdb_options.rs

The signature
```
pub fn new_lru_cache(capacity: size_t) -> Result<Cache, Error> {
```
suggests that failure to allocate memory for the cache can be handled, but this is actually not true. Instead, the throwing `new()` operator from RocksDB will unwind across the FFI boundary, which is UB. Until https://github.com/rust-lang/rust/issues/74990 lands, there is nothing we can do about that.
Since this breaks bc anyway, I also removed the alternative deprecated method for instanciating LRU caches.

Block cache creation failure is not recoverable

---

src/comparator.rs
src/db_options.rs
tests/test_comparator.rs

I have updated the code for supporting comparators as closures.
Reason for this is that moving from functions to closures makes it possible to add more information into the comparator function. Let us for example say one is creating a sql-base and then would like to add a compound index, based on the create index statement. The sort order in the comparator should then depend on the directions of the sorting fields, for example first sort on a float and then an int.
The old solution did not support a way to add meta-info like this into the compare function in a dynamical way and this is currently solved by allowing the comparator to be a closure. By using the move-functionality with closures we can add extra context to the compare function.
The solution is backwards compatible, as it still …

support for comparators as closures

---

src/db.rs
src/db_iterator.rs
tests/test_db.rs

I found a bug in the `DBWALIterator` that would cause it to miss updates in certain scenarios.
One such scenario is calling `latest_sequence_number()` on a newly created DB which returns `0`, then writing a couple of things and calling `get_updates_since(0)`. This would cause the first batch returned by the iterator to be for sequence 2 and not 1 as expected.
The test case I added demonstrates this and fails without my fix.
I also suspect this would cause issues in scenarios where a given sequence number is in the past but no longer exists which causes RocksDB to return an iterator that starts after the sequence number based on the following documentation:
>Sets iter to an iterator that is positioned at a write-batch whose sequence number range [start_seq, end_seq] covers seq_number. If …

Fix bug in `DBWALIterator` that would miss updates

---

src/transactions/transaction.rs

It seems `wi` is not deallocated properly which causes a memory leak when calling `get_writebatch`.
[rocksdb_transaction_get_writebatch_wi](https://github.com/facebook/rocksdb/blob/main/db/c.cc#L5635) allocates memory with `malloc`, which never gets deallocated.
There is [rocksdb_writebatch_wi_destroy](https://github.com/facebook/rocksdb/blob/main/db/c.cc#L2174) but that tries to delete the memory allocated with malloc which is UB and tries to clear `rep`. Using `rocksdb_free` seems to be the right choice.  
There also seems to be unnecessary cloning of the serialized writebatch. The code clones the data once by calling `to_owned` on the slice but the data is also cloned here:
https://github.com/facebook/rocksdb/blob/main/db/c.cc#L1905
To improve that, I think we can just pass the `ptr` …

Fix memory leak when calling get_writebatch and avoid unnecessary clones

---

src/db.rs
tests/test_db.rs

which is critically important for atomic flush use case
Fix https://github.com/rust-rocksdb/rust-rocksdb/issues/792

Expose flush_cfs_opt to flush multiple column families

---

src/db.rs

By forcing the caller to give us an iterator of key references, we can avoid having to clone and allocate one `Box` per input key in `batched_multi_get`, since the keys are already guaranteed to live longer than the function call.
This is a slight breaking change, but IMO an acceptable one which should make any users of `batched_multi_get` happy - the only reason to be using `batched_multi_get` in the first place is to avoid allocations, otherwise one would already use the simpler `multi_get`, which allocates for both keys and return values.
Examples of breaking changes:
```rust
let keys: Vec<String> = vec!["k0".to_string(), "k1".to_string()];
// NOT ALLOWED: owned `Vec` of owned keys
let _ = db.batched_multi_get_cf(&cf, keys, true)
// ALLOWED: borrowed `Vec` of owned keys (`&Vec<T>` …
```

Remove temporary boxed keys in batched_multi_get

---

src/db.rs
tests/test_db.rs

feat: Support column_family_metadata, column_family_metadata_cf

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt
librocksdb-sys/tests/ffi.rs
src/db_options.rs
src/lib.rs
tests/test_db.rs

Release: https://github.com/facebook/rocksdb/releases/tag/v8.5.3
Update mostly for bugfixes. Other changes because facebook/rocksdb@bfdc91017c0667e05cd2f2b49337446e0fb5c1b1 added additional arguments to `rocksdb_options_set_plain_table_factory`.

Update RocksDB to 8.5.3

---

src/lib.rs

`ReadTier` isn't currently public but is required for `ReadOptions::set_read_tier` which is public.
This fixes that minor issue

Expose `ReadTier` publicly

---

src/db_iterator.rs
tests/test_raw_iterator.rs

The PR fixes undefined behaviour described in the #824.

fix: add raw iterator validation before calling next method

---

src/db_options.rs
tests/test_rocksdb_options.rs

Hello!
Fix https://github.com/rust-rocksdb/rust-rocksdb/issues/778
Thanks

feat: Expose set_wal_compression_type

---

src/db_options.rs

From [RocksDB 8.6.0](https://github.com/facebook/rocksdb/blob/main/HISTORY.md#860-08182023):
> Add a new feature to trim readahead_size during scans upto upper_bound when iterate_upper_bound is specified. It's enabled through ReadOptions.auto_readahead_size. Users must also specify ReadOptions.iterate_upper_bound.

feat: Expose set_auto_readahead_size

---

src/db_options.rs

Like the other database option types, it is safe to send and sync this type.

Make `CompactOptions` `Send` and `Sync`

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
src/db_options.rs

changelog: https://github.com/facebook/rocksdb/releases/tag/v8.10.0

Update to RocksDB 8.10.0

---

CHANGELOG.md
src/db_options.rs
src/lib.rs

add WriteBufferManager support, which was recently added in rocksdb C API with https://github.com/facebook/rocksdb/pull/11710 and  https://github.com/facebook/rocksdb/pull/12007

add WriteBufferManager support

---

src/db_options.rs

Current `optimize_for_point_lookup ` has no documentation and has a confusing `cache_size` arg.
This pr copies the [comment from rocksdb](https://github.com/facebook/rocksdb/blob/36704e9227a355fcb8b10bd6d29cf0f9f43d80f8/include/rocksdb/options.h#L83) and renamed the `cache_size` to `block_cache_size_mb` for consistency and clarity.

update doc and arg name for optimize_for_point_lookup

---

src/db_options.rs
src/lib.rs
src/statistics.rs
tests/test_db.rs

This exposes rocksdb statistics (tickers and histograms) to allow rust-rocksdb users to introspect individual metrics. Additionally, this PR also adds `set_statistics_level(StatsLevel)` to `Options` for fine-grain control over which stats are collected.
Tickers and histograms are available in `rocksdb::statistics::{Ticker, Histogram}` with the necessary helpers to convert the ticker type to the corresponding rocksdb name (and vice-versa via the `FromStr` trait).
Test Plan:
- New test added in test_db.rs
- Sanity check unit tests in statistics.rs

Expose rocksdb cumulative statistics and histograms

---

src/db_options.rs

Make `FlushOptions` `Send` and `Sync`

---

src/perf.rs

Current API design doesn't make it possible for users to get memory usage if they use optimistic transaction database. This change exposes `MemoryUsageBuilder` builder type and the raw `MemoryUsage` type to fix this.
Alternatively, we can make `perf::get_memory_usage()` be parametrized on `<T: ThreadMode, D: DBInner>` but that requires the `DBInner` trait to be exported as well.

Export memory usage builder and MemoryUsage structs to users

---

src/transactions/transaction_db.rs

This PR aims to resolve an issue encountered when using the nightly toolchain for building. An error arises indicating a violation of the safety precondition for `ptr::copy_nonoverlapping`. Although the documentation for [`ptr::copy_nonoverlapping`](https://doc.rust-lang.org/std/ptr/fn.copy_nonoverlapping.html#safety) does not explicitly state that the `src` pointer needs to be non-null, the implementation mandates it. This issue appears to stem from the changes introduced by https://github.com/rust-lang/rust/pull/121662.
Here's the stderr using `nightly-2024-03-12` toolchain:
```stderr
thread 'main' panicked at library/core/src/panicking.rs:156:5:
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified …
```

Ensure non-null pointers for `ptr::copy_nonoverlapping`

---

src/backup.rs
tests/test_backup.rs

BackupEngine is a simple pointer wrapper, so it's safe to send to another thread since the underlying RocksDB backup engine is thread-safe.

Make BackupEngine Send

---

librocksdb-sys/build.rs

When building for the riscv64gc-unknown-linux-gnu target I was getting the link-time error 
```
error: linking with `riscv64-linux-gnu-g++` failed: exit status: 1
...
undefined reference to `__atomic_compare_exchange_1'
```
This is fixed by adding the following to the build.rs

Add linking libatomic command to build.rs to allow building for riscv64gc-unknown-linux-gnu target

---

src/transactions/optimistic_transaction_db.rs
tests/test_optimistic_transaction_db.rs

I've found that it's easy enough to add range deletion to the optimistic transaction DB, however, I wouldn't mind having this code checked by a more experienced member of the community.

Add delete_range to OptimisticTransactionDB

---

CHANGELOG.md
src/db.rs
src/transactions/optimistic_transaction_db.rs

Previously, the default column family was initialized with default settings if not explicitly included in the column family descriptors. This commit ensures that the default column family inherits the open options

!fix: Ensure default column family uses specified open options

---

rust-toolchain.toml

in CI, we specify the rust version as 1.70.0...
```yaml
on: [push, pull_request]
env:
RUST_VERSION: 1.70.0
```
likewise, the package manifest pins the rust version...
```toml
rust-version = "1.70.0"
```
..but this version is not pinned by cargo, via a `rust-toolchain`. this means that testing this project using the stable toolchain by default (_at time of writing, this is 1.78.0_) will see test failures due to error messages not matching the expected snapshots, due to `rustc` itself making changes to its diagnostics:
```
test tests/fail/snapshot_outlive_db.rs ... mismatch
EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0597]: `db` does not live long enough
--> tests/fail/snapshot_outlive_db.rs:6:9
|
4 |     let _snapshot = {
|         --------- borrow later …
```

toolchain: 📌 pin toolchain to rust `1.70.0`

---

librocksdb-sys/Cargo.toml

A new version of LZ4 is out.
- https://github.com/lz4/lz4/releases/tag/v1.10.0
- https://crates.io/crates/lz4-sys/1.10.0

Bump lz4 1.10

---

src/comparator.rs
src/db_options.rs
tests/test_comparator.rs
tests/test_db.rs
tests/test_sst_file_writer.rs
tests/util/mod.rs

Closes: #904 
1. Fixes a memory bug in the following methods:
- `ReadOptions::set_timestamp`
- `ReadOptions::set_iter_start_ts`
- `CompactOptions::set_full_history_ts_low`
2. Modify the `Options::set_comparator` API, allowing users to choose their own timestamp and comparator implementations (unlike in #901, which forces using big endian u64).

Improvements to user defined timestamp

---

src/column_family.rs

See https://github.com/rust-rocksdb/rust-rocksdb/issues/407#issuecomment-1635967796 for justification on safety. This is a significant blocker to multi-threaded code.
closes #407

Implement `Sync` for `{Bound}ColumnFamily`

---

.github/workflows/rust.yml

The transitive dependency `clap` [requires](https://github.com/rust-rocksdb/rust-rocksdb/actions/runs/10226961920/job/28297861026) rustc 1.74.0 or above.

Fix cargo audit check in github actions ci

---

src/compaction_filter.rs
src/compaction_filter_factory.rs

I needed this patch for the Debian package of the `rocksdb` crate, as when we run the tests the current working directory is not writable.
I'm not a Rust developer at all, please let me know if there is a better way to do this.
Thank you!

Fix two tests that want to write to the current working directory

---

src/db.rs
src/transactions/transaction_db.rs

When callers are executing code like:
```rust
// Check if the column family already exists.
if let Some(cf) = self.borrow_db().cf_handle(state_type) {
return Ok(cf);
}
// Create the column family if it doesn't exist.
let create_result = block_in_place(|| {
self.borrow_db()
.create_cf(state_type, &create_column_family_options())
});
```
...they might reasonably expect that if the call fails with `InvalidArgument`, and the reason for the `InvalidArgument` was "Column family already exists", then upon retrying like so:
```rust
match create_result {
Ok(()) => (),
Err(e) => {
if e.kind() == rocksdb::ErrorKind::InvalidArgument {
// We might have lost a race to create the column family.
if let Some(cf) = self.borrow_db().cf_handle(state_type) {
return Ok(cf);
}
}
return Err(format!(
"Failed to …
```

Fix column family creation race.

---

librocksdb-sys/build.rs

This change adds a define for ROCKSDB_SCHED_GETCPU_PRESENT in the Linux-specific section of the build script. This ensures that the RocksDB library is aware of the presence of the sched_getcpu function on Linux systems, potentially optimizing CPU scheduling.

fix(build): add ROCKSDB_SCHED_GETCPU_PRESENT for Linux build config

---

src/db.rs
src/db_options.rs
tests/test_rocksdb_options.rs

This exposes the rocksdb_get_db_identity function, which calls DB::GetDbIdentity. It also adds a setter and accessor to Options to change the option.
This function is useful to determine if two RocksDB copies originated from the same place.

DB: Implement get_db_identity using rocksdb_get_db_identity

---

src/db_options.rs
tests/test_rocksdb_options.rs

This was added to the C API in RocksDB 9.7.0. The RocksDB wiki recommends setting this option to true:
"We recommend to set track_and_verify_wals_in_manifest to true for production, it has been enabled in production for the entire database cluster serving the social graph for all Meta apps."
See: https://github.com/facebook/rocksdb/wiki/Track-WAL-in-MANIFEST

Options: Add set_track_and_verify_wals_in_manifest

---

README.md

- `README.md:61`: "dependecy" corrected to "dependency".
- Improved documentation accuracy and ensured professionalism by fixing the typo.

typo-Update README.md

---

librocksdb-sys/build.rs
src/backup.rs
src/checkpoint.rs
src/column_family.rs
src/db_iterator.rs
src/db_options.rs
src/db_pinnable_slice.rs
src/snapshot.rs
src/sst_file_writer.rs
src/transactions/transaction.rs
tests/test_db.rs

* One unnescessary borrow
* Some named lifetimes that can be elided
* Wanted/unwanted lists in doc comments
* A test with `mem::transmute` to extend lifetimes where clippy recommends type annotations (rewritten to use scoped threads instead)

Fix future clippy warnings

---

CHANGELOG.md

**Fix Typo in `CHANGELOG.md`**
This pull request corrects a minor typo in the `CHANGELOG.md` file. The word "mathod" has been updated to "method" for clarity and accuracy.
- **File Modified:** `CHANGELOG.md`
- **Summary of Changes:**  
- Corrected "mathod" to "method" in the description of `path` for the `DB` type.
This is a documentation-only update aimed at improving clarity and professionalism in the project's changelog.
---
**Allow edits by maintainers:** [x]

 typo fix Update CHANGELOG.md

---

librocksdb-sys/src/test.rs

Hello.
Some of the tests that were re-enabled in v0.17 of librocksdb-sys fail to compile on at least arm64, armel and riscv64 on Debian infrastructure due to a bad argument type (`error[E0308]: mismatched types`, `expected *const i8, found *mut u8`):
- https://ci.debian.net/packages/r/rust-librocksdb-sys/testing/arm64/56531952/
- https://ci.debian.net/packages/r/rust-librocksdb-sys/testing/armel/56531584/
- https://ci.debian.net/packages/r/rust-librocksdb-sys/testing/riscv64/56538194/
This PR uses libc's `c_char` instead of `i8` as the argument of `error_message` so as to match the corresponding variable in `internal`.
Cheers!

Fix error_message argument type

---

librocksdb-sys/build.rs

To build on AIX, we need to set `OS_AIX` macro as well as link against `libc++abi`.

Support builds on AIX

---

librocksdb-sys/build.rs

Hard-coding the C++ library linking is bad practice, and instead this crate needs to follow the practices as described under https://docs.rs/cc/1.2.14/cc/index.html#c-support.
Without doing so, this crate will not compile on when using libc++ instead of libstdc++.
This change will keep the existing behaviour, while allowing downstream consumers of this crate to override the C++ library with the `CXXSTDLIB` which is respected by the cc crate.

Fix C++ linking

---

src/backup.rs
src/db_options.rs

I'd like to set this sync flag in [Qdrant](https://github.com/qdrant/qdrant). Enabling this well invoke `fsync(2)` when recovering a RocksDB backup, helping with durability.
It's roughly described here: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB#advanced-usage

Add function to set sync flag in backup engine options

---

src/db_iterator.rs

Edit the rustdoc for both DBRawIteratorWithThreadMode and DBIteratorWithThreadMode to clarify what they do, and link to each other.

doc db_iterator.rs: Minor edits to rustdoc; more links

---

.github/workflows/rust.yml
librocksdb-sys/build.rs

`WITH_JEMALLOC` is not recognized by rocksdb.
`ROCKSDB_JEMALLOC` is the correct one.

Define correct name for jemalloc

---

librocksdb-sys/Cargo.toml

`zstd-sys`'s default feature `bindgen` enables bindgen `runtime` feature, resulting in compile failure when using `bindgen-static`:
```
`runtime` and `static` features can't be combined
```
disable the `bindgen` feature of [`zstd-sys`](https://github.com/gyscos/zstd-rs/blob/main/zstd-safe/zstd-sys/Cargo.toml) which is enabled by default:
zstd-sys/Cargo.toml
```
[features]
default = ["legacy", "zdict_builder", "bindgen"]
```
This won't affect anything as the binding is pre-generated
```
This library includes a pre-generated bindings.rs file. You can also generate new bindings at build-time, using the bindgen feature:
cargo build --features bindgen
```

Fix bindgen-static build

---

src/db_options.rs

RocksDB 10.2.1 is marking this API as deprecated. The upstream documentation has changed to state the following. Update rustdoc to match, and mark with #[deprecated]. Currently rust-rocksdb is not using this version of RocksDB, but presumably it will eventually, so we might as well mark this as deprecated now.
Upstream RocksDB comment:
```
// DEPRECATED: This option might be removed in a future release.
// There should be no noticeable performance difference whether this option
// is turned on or off when a DB does not use DeleteRange().
```
https://github.com/facebook/rocksdb/blob/v10.2.1/include/rocksdb/options.h#L1837

db_options.rs: deprecate set_ignore_range_deletions (RocksDB 10.2.1)

---

src/ffi_util.rs

The original `opt_bytes_to_ptr` function accepts a parameter of type `Option<T> where T: AsRef<[u8]>`. While this is flexible, it also allows owned types like `String` or `Vec<u8>` to be passed in. Since the function takes ownership of T, any owned data (like a `String`) will be dropped at the end of the function scope.
This results in undefined behavior, as the returned `*const c_char` pointer may point to memory that is already freed, leading to dangling pointers.
See the example below:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=a59bc55798c258040f5aa04c9e60c1b5
To resolve this, the function should accept a borrowed reference instead, such as:
The function no longer takes ownership of the data.
The returned pointer is guaranteed to be valid for at least as …

ffi_util.rs: improve opt_bytes_to_str to fix (#693)

---

src/lib.rs
src/write_batch.rs
tests/test_db.rs
tests/test_write_batch.rs

By the way, when using the WriteBatchIterator, remove the dynamic trait (dyn) and switch to static dispatch.

Implement WriteBatchIteratorCf trait and update related methods for compatibility

---

librocksdb-sys/build.rs
src/db_options.rs
tests/test_column_family.rs
tests/test_comparator.rs
tests/test_db.rs
tests/test_merge_operator.rs
tests/test_optimistic_transaction_db_memory_usage.rs
tests/test_transaction_db_memory_usage.rs

This fixes clippy warnings when using the newest stable release of Rust. These are backwards-compatible, so seem worth fixing now. Most of the warnings are formatting strings, such as the following:
```
warning: variables can be used directly in the `format!` string
--> librocksdb-sys/build.rs:393:19
|
393 |         Err(e) => panic!("Command failed with error: {}", e),
```
There was one unnecessary semicolon on `src/db_options.rs:2735`.
There is one clippy warning remaining with Rust 1.88: Using Debug for a Path (`src/db.rs:2645`). I left this unchanged.

Run cargo clippy --fix with Rust 1.88

---

src/compaction_filter.rs
src/compaction_filter_factory.rs
src/comparator.rs
src/db.rs
src/db_options.rs
src/ffi_util.rs
src/merge_operator.rs
src/prop_name.rs
src/slice_transform.rs
src/write_batch.rs

Rust 2024 now warns when performing unsafe operations inside unsafe functions. This change adds unsafe blocks from cargo --fix, to make it easier to eventually upgrade this crate to Rust 2024.
See:
https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html

unsafe changes from cargo --fix with Rust 2024

---

librocksdb-sys/src/lib.rs
tests/test_rocksdb_options.rs

On Unix systems, RocksDB itself only declares weak references to jemalloc symbols ([example](https://github.com/facebook/rocksdb/blob/13f054febb26100184eeefaac11877d735d45ac2/port/jemalloc_helper.h#L60-L61)) – even if `ROCKSDB_JEMALLOC` is defined properly. As such, unless the program has a separate strong reference to jemalloc, the linker will decide that linking jemalloc is unnecessary.
Force the linker to treat jemalloc as necessary by adding a `extern crate` declaration, similar to existing system crates.
Tested via https://github.com/timothyg-stripe/rust-rocksdb-1026:
> Before:
>
> ```
> $ nm target/debug/server | grep mallocx
>                  w mallocx
> $ target/debug/server && grep Jemalloc /tmp/rocksdb-test/LOG
> Opened the db
> 2025/08/09-17:12:32.621073 2437467 Jemalloc …
```

Ensure jemalloc is linked in when the feature is enabled

---

src/transactions/options.rs

- Replaced incorrect logic with the proper FFI call `rocksdb_transaction_options_set_skip_prepare`.
- Ensures `skip_prepare` option is correctly applied when configuring RocksDB transactions.

fix: use correct FFI setter for skip_prepare in RocksDB transaction options
