rust-rocksdb/rust-rocksdb

README.md
src/comparator.rs
src/ffi.rs
src/lib.rs
src/main.rs
src/merge_operator.rs
src/rocksdb.rs

Also cleans up the public API.
Still to come is documentation and tests.

Add Iterators and Snapshots

---

Cargo.toml
src/main.rs
src/rocksdb.rs
test/test.rs
test/test_iterator.rs

Switch to boxed values for safety and add integration tests

---

src/rocksdb.rs
test/test.rs
test/test_multithreaded.rs

Allow RocksDB to be shared across threads

---

src/lib.rs
src/main.rs
test/test_column_family.rs
test/test_iterator.rs
test/test_multithreaded.rs

Fix all warnings

---

README.md

This is the same as using ^, which is a bit nicer than ~ imho, and is the default for a reason :)

Use more regular semver suggestion

---

src/ffi.rs
src/rocksdb.rs

Due to this [breakage](https://github.com/rust-lang/rust/issues/29867) ARM doesn't work out of the box.

Fix compilation on ARM for Rust >= 1.6

---

src/comparator.rs
src/merge_operator.rs
src/rocksdb.rs

1. Remove dead code.
2. Remove unnecessary unsafe
"cargo build" is happy now :)

*: Tiny clean up.

---

src/rocksdb.rs

Fix https://github.com/spacejam/rust-rocksdb/issues/42

support snapshot get/get_cf

---

src/ffi.rs

Two more ARM-specific fixes

---

src/rocksdb.rs

I've been adding some documentation as I'm learning about the library. Not much, but it might be useful to someone else.

Added some documentation

---

src/lib.rs
src/rocksdb_options.rs

Part of #69, but also applies to existing options methods

Doctests for Options methods

---

src/rocksdb.rs

This shouldn't break backwards compatibility for the open/destroy/repair methods. The return type of the ``path()`` method has been changed, however

Use PathBuf/Path type for file paths

---

src/ffi_util.rs
src/rocksdb.rs

Fixes #96 
* Update ffi_util.rs
* Update rocksdb.rs

Fix: https://github.com/spacejam/rust-rocksdb/issues/96

---

src/compaction_filter.rs
src/db.rs
src/db_options.rs
src/ffi_util.rs
src/lib.rs

Add set_compaction_filter to Options and compact_range to Db.

Compaction filter

---

src/lib.rs

I think that this will resolve the issues in #113.

Expose ReadOptions from DB

---

src/lib.rs

These seem like useful functions we could add without much downside.

Implement Clone and AsRef<str> for Error

---

src/db.rs
tests/test_column_family.rs

list column families

---

src/db_options.rs

I found this knob to be quite helpful for improving sequential iterator performance.

Expose advise_random_on_open option

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs

Update bindgen to 0.37

---

src/db_options.rs

Source: https://github.com/facebook/rocksdb/blob/bde1c1a72afe365240004d5b75d61004618110bb/db/c.cc#L2233-L2236

Add DBOptions.set_wal_dir

---

src/db_options.rs

From https://github.com/facebook/rocksdb/blob/bde1c1a72afe365240004d5b75d61004618110bb/include/rocksdb/options.h#L687-L695.

Expose compaction_readahead_size option

---

src/db.rs
src/db_options.rs
src/lib.rs
tests/test_iterator.rs

See https://github.com/facebook/rocksdb/wiki/MemTable for more information.

Add support for customizing the memtable factory

---

src/db.rs

I found out that on macOS test `test_column_family` is crashing with error: 
```
error: process didn't exit successfully: `rust-rocksdb/target/debug/deps/test_column_family-f00ad08f9f74dcc8` (signal: 11, SIGSEGV: invalid memory reference)
```

Fixed crash `test_column_family` test on macOS

---

.gitignore
librocksdb-sys/.gitignore

Removed a redundant file `librocksdb-sys/.gitignore` and added some entries into a `./.gitinore` file.

Some changes in a .gitignore file

---

src/db.rs

This should allow changing options (e.g. `disable_auto_compactions`) without closing and re-opening the database.

Allow setting options on the DB

---

src/db_options.rs
src/lib.rs

See https://github.com/facebook/rocksdb/wiki/PlainTable-Format.

Add support for plain table factories

---

src/db.rs
tests/test_property.rs

Adds support for `rocksdb_property_value` and `rocksdb_property_value_cf`.

Add property getters

---

src/backup.rs

This PR implements restoring DB from the latest backup.  
Resolves issue# https://github.com/rust-rocksdb/rust-rocksdb/issues/135

Support for restore from the backup

---

src/db.rs

Added after Discussion with @iSynaptic https://github.com/rust-rocksdb/rust-rocksdb/issues/273

Added a function to create iterator with specific CF and ReadOptions

---

CONTRIBUTING.md

https://github.com/rust-rocksdb/rust-rocksdb/issues/216
Looked at several example contribution guides for inspiration, including the one referenced in the issue.

adds contribution guide

---

librocksdb-sys/build.rs

Same with https://github.com/rust-rocksdb/rust-rocksdb/pull/167, some comments are borrows from the PR.

enable sse4.2/pclmul for accelerated crc32c

---

CHANGELOG.md
src/db.rs
tests/test_db.rs

Add `DB::latest_sequence_number` method.

---

src/db.rs

This allows handling errors when they're encountered during iteration of
the DB. The details of RocksDB iterator error reporting is described in
https://github.com/facebook/rocksdb/wiki/Iterator#error-handling
This method alone is not especially ergonomic or idiomatic for rust:
users would have to call `status` on their iterators whenever they
receive a `None` item to check whether iteration actually failed instead
of simply ended. A more complete approach is to change the iterator
signature to `Item = Result<..., Error>` and internally have the
iterator check its status. This better reflects the fact that an error
can be encountered during iteration, and that the user should handle or
propagate them explicitly. Such an approach would however be a breaking
change, and should be approached …

Expose the `status` method on iterators

---

librocksdb-sys/build.rs

Use `-DOS_ANDROID` on Android.

Add Android support

---

src/db.rs
src/db_options.rs
tests/test_rocksdb_options.rs

options: add set_verify_checksums and set_level_compaction_dynamic_level_bytes

---

src/db.rs

DB::repair: pass Options by ref

---

CHANGELOG.md

Decompression speed was improved in 1.9
https://github.com/lz4/lz4/releases

Update lz4 to v1.9.2

---

CHANGELOG.md
src/db_options.rs
tests/test_rocksdb_options.rs

https://github.com/facebook/rocksdb/blob/f059c7d9b96300091e07429a60f4ad55dac84859/include/rocksdb/table.h#L249-L274

Expose format version

---

src/db.rs

Reuse the to_cpath function and avoid unnecessary line break.

Minor cleanup in db.rs

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs

Bump uuid and bindgen dependencies

---

src/db_options.rs

adds options that I have in use in a go version of the current library I'm working on: 
* set_pipelined_write,
* memtable_huge_page_size 
* optimize_universal_style_compaction

Add some extra config options

---

src/db.rs

This change exposes the range delete C APIs added in https://github.com/facebook/rocksdb/pull/6259.

Add support for range delete APIs

---

src/db_iterator.rs

Fix doc for DBRawIterator::prev and next

---

librocksdb-sys/build.rs

Fix build on windows host

---

tests/test_db.rs

@aleksuss had some good points in #406 regarding test formatting. Since that PR was merged before I saw them, I decided to open a new PR to address them.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Cleanup tests.

---

src/db.rs
tests/test_db.rs

This api allows you to open a database with a TTL filter. 
This filter is applied during compaction, and entries get dropped if their TTL has expired.
This is based on the current RocksDB C bindings that don't expose additional functionality from the ttl utilities.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Expose `open_with_ttl`.

---

src/db_options.rs

Add set_max_log_file_size and set_recycle_log_file_num to the Options

---

CHANGELOG.md
src/column_family.rs
src/db.rs
src/lib.rs
tests/test_column_family.rs

The changes are covered by the `test_column_family` test.

Export DEFAILT_COLUMN_FAMILY_NAME constant

---

src/compaction_filter.rs
src/compaction_filter_factory.rs
src/db_options.rs
src/lib.rs

And other option configuration.

Add compaction filter factory API

---

librocksdb-sys/build.rs

This fix build when using prebuilt RocksDB

Link C++ stdlib when using prebuilt rocksdb

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

Any chance to get this published soon? :)

librocksdb-sys: update rocksdb to 6.11.4

---

CHANGELOG.md
src/db.rs

Add DB::cancel_all_background_work method

---

librocksdb-sys/Cargo.toml

Nothing tested, but for the build tests

bump bindgen version

---

src/db.rs
tests/test_db.rs

Following https://github.com/rust-rocksdb/rust-rocksdb/pull/238.

Allow setting options on a ColumnFamily

---

CHANGELOG.md
src/db.rs
tests/test_db.rs

Add multi_get functions family

---

src/db.rs
tests/test_db.rs

Add 'key_may_exist' functions family

---

CHANGELOG.md
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

Upgrades librocksdb-sys to 6.20.3.

Upgrade librocksdb-sys to 6.20.3

---

src/db_options.rs

One more useful option from #260.

Add BlockBasedOptions::set_whole_key_filtering()

---

src/db_options.rs
tests/test_db.rs

Documentation based on http://rocksdb.org/blog/2021/05/26/integrated-blob-db.html

feat: add BlobDB options

---

librocksdb-sys/src/test.rs
src/backup.rs
src/db.rs
src/db_options.rs
src/perf.rs
src/slice_transform.rs
tests/test_merge_operator.rs

Signed-off-by: Federico Guerinoni <guerinoni.federico@gmail.com>

Fix clippy warnings

---

librocksdb-sys/build.rs

These offer slight speedups mostly in the Ribbon filter implementation.
* https://github.com/facebook/rocksdb/blob/a6a179859e612856f9de8b7667dd0a2cfddd286a/build_tools/build_detect_platform#L711-L718
* https://github.com/facebook/rocksdb/blob/a6a179859e612856f9de8b7667dd0a2cfddd286a/build_tools/build_detect_platform#L805

Use more target features to build librocksdb-sys

---

src/backup.rs
src/checkpoint.rs
src/db_options.rs

ffi_util::to_cpath exists to convert Path into a CString so use it
in all places where that conversion is needed.  This removes bunch of
code duplication.  Slight downside is that error messages in a few
places loose some context.

Consistently use ffi_util::to_cpath to convert Path to CString

---

src/db.rs
tests/test_db.rs

RocksDB has an optimized version of MultiGet API that handle the read requests in batches so that multiple gets can be satisfied by the same file read.  But the feature is available in neither C nor rust API.
The batched version of MultiGet for C API is available in [rocksdb-9952](https://github.com/facebook/rocksdb/pull/9952).  Once it has been merged, it should be available in the next RocksDB release.
This PR includes the draft version of the batched MultiGet for rust API.  Once the above PR is merged, I will turn this PR into ready for review.
This PR depends on https://github.com/rust-rocksdb/rust-rocksdb/pull/645 that upgrades rocksdb to v7.3.1.

Add batched version MultiGet API

---

librocksdb-sys/build.rs
src/db.rs

Tested on my local device, assumes building on macos, which I believe is a requirement anyway.
Based on #637

feat: enable IOS building

---

src/db_options.rs

It was updated quite a long time ago upstream, I thought it might be beneficial to update it in docs here too: https://github.com/facebook/rocksdb/commit/65cd6cd4b62cbcb8f234bc3d6d25b7241b3ee55c

Update set_use_fsync comment

---

librocksdb-sys/Cargo.toml

> # 0.5.0 - 2022-05-19
>
> - Update jemalloc to 5.3.0 (tikv/jemallocator#23)

Bump tikv-jemalloc-sys to 0.5

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

Release notes: https://github.com/facebook/rocksdb/releases/tag/v7.4.4

Bump rocksdb to 7.4.4 (closes #571)

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs
src/db.rs
src/ffi_util.rs
src/transactions/optimistic_transaction_db.rs
src/transactions/transaction_db.rs
tests/test_checkpoint.rs
tests/test_column_family.rs
tests/test_db.rs
tests/test_iterator.rs
tests/test_merge_operator.rs

Bump bindgen 0.63.0 -> 0.64.0

---

librocksdb-sys/build.rs

updated ios min version to 12

---

src/db.rs
src/ffi_util.rs
tests/test_db.rs

Add a method `key_may_exist_cf_opt_value()` that also returns value if the value is found compared to `key_may_exist_cf_opt()`.

Retrieve Value from `KeyMayExist` if value found in Cache or Memory

---

src/db.rs
src/db_options.rs
src/ffi_util.rs
src/perf.rs

Just cosmetics/consistency. No functional change.

Prefer rocksdb_free to free for RocksDB memory

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs
librocksdb-sys/build_version.cc

Release notes: https://github.com/facebook/rocksdb/releases/tag/v8.3.2

Update to RocksDB 8.3.2

---

src/db_options.rs

fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/807

feat: Expose set_optimize_filters_for_memory

---

src/db_options.rs

Fixes https://github.com/rust-rocksdb/rust-rocksdb/issues/515

feat: Expose compression option parallel_threads

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

changelog: https://github.com/facebook/rocksdb/releases/tag/v8.9.1

Update RocksDB to 8.9.1

---

Cargo.toml
librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
src/db_options.rs
src/statistics.rs

changelog: https://github.com/facebook/rocksdb/releases/tag/v9.0.0

Update to RocksDB 9.0.0

---

README.md

As mentioned in #865 this PR adds a section in README about the mt_static feature so that the points and usage of the feature are clear.

Chore: Description for mt_static feature

---

Cargo.toml
README.md
librocksdb-sys/Cargo.toml
librocksdb-sys/build.rs

see: https://github.com/rust-rocksdb/rust-rocksdb/pull/867#issuecomment-2008394596

Revert portable feature as it doesn't do anything

---

src/db_options.rs
tests/test_rocksdb_options.rs

This PR adds support for enabling blob caching.

Add support for enabling blob cache

---

src/transactions/transaction_db.rs
tests/test_transaction_db_property.rs

feat: Properties for TransactionDB #899

---

librocksdb-sys/build.rs

Without this, it causes an unnecessary build of RocksDB that seems to never work.
<details>
<summary>Sample of build errors</summary>
```
cargo:warning=In file included from rocksdb/memory/jemalloc_nodump_allocator.cc:6:
cargo:warning=In file included from rocksdb/memory/jemalloc_nodump_allocator.h:11:
cargo:warning=rocksdb/port/jemalloc_helper.h:62:61: error: use of undeclared identifier 'nothrow'; did you mean 'std::nothrow'?
cargo:warning=   62 | extern "C" JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW *
cargo:warning=      |                                                             ^
cargo:warning=rocksdb/port/jemalloc_helper.h:50:40: note: expanded from macro 'JEMALLOC_NOTHROW'
cargo:warning=   50 | #define JEMALLOC_NOTHROW JEMALLOC_ATTR(nothrow)
cargo:warning= …
```

use the provided system rocksdb prebuilt on freebsd

---

.github/workflows/rust.yml

[CI] Deprecated Node version and outdated GitHub Actions

---

librocksdb-sys/Cargo.toml
librocksdb-sys/tests/ffi.rs

[SEC] RUSTSEC-2023-0020: const-cstr is Unmaintained

---

src/perf.rs
tests/test_optimistic_transaction_db_memory_usage.rs
tests/test_transaction_db_memory_usage.rs

Related to:
- https://github.com/rust-rocksdb/rust-rocksdb/issues/910

TransactionDB support in MemoryUsageBuilder

---

.github/workflows/rust.yml
Cargo.toml
README.md
librocksdb-sys/Cargo.toml

Add features `bindgen-runtime` (the default) and `bindgen-static`.
(Some of these changes are auto-formatting).

Allow using static bindgen feature

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

https://github.com/facebook/rocksdb/releases/tag/v9.9.3

Update to RocksDB 9.9.3

---

librocksdb-sys/Cargo.toml
librocksdb-sys/build_version.cc
librocksdb-sys/rocksdb_lib_sources.txt

https://github.com/facebook/rocksdb/releases/tag/v9.10.0

Update to RocksDB 9.10.0

---

CONTRIBUTING.md
README.md
librocksdb-sys/README.md

Hello
While looking through your docs I found and fixed several spelling issues.
Br,Elias.

Docs fix spelling issues

---

src/write_batch.rs
tests/test_write_batch.rs

What does this PR do?
---------------------
- Add support for `WriteBatch::put_log_data`
Motivation
----------
Have `put_log_data` available to handle some replication use cases (as described in https://github.com/facebook/rocksdb/wiki/Replication-Helpers)

WriteBatch: add support for WriteBatch::put_log_data

---

README.md

fix Update README.md

---

src/db.rs
src/lib.rs
tests/test_db.rs

https://github.com/rust-rocksdb/rust-rocksdb/issues/997
Mostly copied from https://github.com/tikv/rust-rocksdb/blob/master/src/rocksdb.rs#L1366

Add get_approximate_sizes

---

librocksdb-sys/build.rs

Closes #991 
As there doesn't seem to be much motion on fixing the issue upstream I'd like so suggest adding the workaround by @tekacs - https://github.com/pervasiveapp/rust-rocksdb/commit/c8badb894fa63271d4b894d29466b60feda26a84

Support GCC 15

---

src/db.rs
tests/test_db.rs

feat: expose {enable,disable}_file_deletions

---

src/db_options.rs
tests/test_rocksdb_options.rs

Expose set_cache_index_and_filter_blocks_with_high_priority() block option setter.

feat: set_cache_index_and_filter_blocks_with_high_priority
